// Generated by gencpp from file j2_mono/Polygon.msg
// DO NOT EDIT!


#ifndef J2_MONO_MESSAGE_POLYGON_H
#define J2_MONO_MESSAGE_POLYGON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <j2_mono/Point.h>

namespace j2_mono
{
template <class ContainerAllocator>
struct Polygon_
{
  typedef Polygon_<ContainerAllocator> Type;

  Polygon_()
    : pts()  {
    }
  Polygon_(const ContainerAllocator& _alloc)
    : pts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::j2_mono::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::j2_mono::Point_<ContainerAllocator> >::other >  _pts_type;
  _pts_type pts;




  typedef boost::shared_ptr< ::j2_mono::Polygon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::j2_mono::Polygon_<ContainerAllocator> const> ConstPtr;

}; // struct Polygon_

typedef ::j2_mono::Polygon_<std::allocator<void> > Polygon;

typedef boost::shared_ptr< ::j2_mono::Polygon > PolygonPtr;
typedef boost::shared_ptr< ::j2_mono::Polygon const> PolygonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::j2_mono::Polygon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::j2_mono::Polygon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace j2_mono

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'j2_mono': ['/home/riki/AdasWork/catkin_ws/src/j2_mono/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::j2_mono::Polygon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::j2_mono::Polygon_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2_mono::Polygon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2_mono::Polygon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2_mono::Polygon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2_mono::Polygon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::j2_mono::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9d7e166d449653c48720f55c89cbced";
  }

  static const char* value(const ::j2_mono::Polygon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9d7e166d449653cULL;
  static const uint64_t static_value2 = 0x48720f55c89cbcedULL;
};

template<class ContainerAllocator>
struct DataType< ::j2_mono::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "j2_mono/Polygon";
  }

  static const char* value(const ::j2_mono::Polygon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::j2_mono::Polygon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point[] pts\n\
\n\
================================================================================\n\
MSG: j2_mono/Point\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::j2_mono::Polygon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::j2_mono::Polygon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Polygon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::j2_mono::Polygon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::j2_mono::Polygon_<ContainerAllocator>& v)
  {
    s << indent << "pts[]" << std::endl;
    for (size_t i = 0; i < v.pts.size(); ++i)
    {
      s << indent << "  pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::j2_mono::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.pts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // J2_MONO_MESSAGE_POLYGON_H
