// Generated by gencpp from file j2_mono/Rect.msg
// DO NOT EDIT!


#ifndef J2_MONO_MESSAGE_RECT_H
#define J2_MONO_MESSAGE_RECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace j2_mono
{
template <class ContainerAllocator>
struct Rect_
{
  typedef Rect_<ContainerAllocator> Type;

  Rect_()
    : left(0.0)
    , top(0.0)
    , right(0.0)
    , bottom(0.0)  {
    }
  Rect_(const ContainerAllocator& _alloc)
    : left(0.0)
    , top(0.0)
    , right(0.0)
    , bottom(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _top_type;
  _top_type top;

   typedef float _right_type;
  _right_type right;

   typedef float _bottom_type;
  _bottom_type bottom;




  typedef boost::shared_ptr< ::j2_mono::Rect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::j2_mono::Rect_<ContainerAllocator> const> ConstPtr;

}; // struct Rect_

typedef ::j2_mono::Rect_<std::allocator<void> > Rect;

typedef boost::shared_ptr< ::j2_mono::Rect > RectPtr;
typedef boost::shared_ptr< ::j2_mono::Rect const> RectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::j2_mono::Rect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::j2_mono::Rect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace j2_mono

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'j2_mono': ['/home/riki/AdasWork/catkin_ws/src/j2_mono/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::j2_mono::Rect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::j2_mono::Rect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2_mono::Rect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::j2_mono::Rect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2_mono::Rect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::j2_mono::Rect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::j2_mono::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7aad971742c7cc38deb20cfb704affa1";
  }

  static const char* value(const ::j2_mono::Rect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7aad971742c7cc38ULL;
  static const uint64_t static_value2 = 0xdeb20cfb704affa1ULL;
};

template<class ContainerAllocator>
struct DataType< ::j2_mono::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "j2_mono/Rect";
  }

  static const char* value(const ::j2_mono::Rect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::j2_mono::Rect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n\
float32 top\n\
float32 right\n\
float32 bottom\n\
";
  }

  static const char* value(const ::j2_mono::Rect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::j2_mono::Rect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.top);
      stream.next(m.right);
      stream.next(m.bottom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Rect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::j2_mono::Rect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::j2_mono::Rect_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "top: ";
    Printer<float>::stream(s, indent + "  ", v.top);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "bottom: ";
    Printer<float>::stream(s, indent + "  ", v.bottom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // J2_MONO_MESSAGE_RECT_H
