int64 vehSpeed # km/h 
int64 vehSpeed_time_stamp
int64 wheelAngle # rad
int64 wheelAngle_time_stamp
int64 gearType  # GEAR_TYPE_N = 0, GEAR_TYPE_P = 1, GEAR_TYPE_R = 2, GEAR_TYPE_D = 3
int64 gearType_time_stamp
int64 turnSignal # TURN_SIGNAL_NONE = 0, TURN_SIGNAL_LEFT = 1, TURN_SIGNAL_RIGHT = 2, TURN_SIGNAL_DOUBLE = 3
int64 turnSignal_time_stamp
float32 acc # m/s^2
float32 yaw
float32 yaw_rate # rad/s
int64 imu_time_stamp
