# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from j2_mono/OBBox2D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import j2_mono.msg

class OBBox2D(genpy.Message):
  _md5sum = "20845fd799692f5fd377b5118d47def7"
  _type = "j2_mono/OBBox2D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Point corner
Point axes_pts
float32 size

================================================================================
MSG: j2_mono/Point
float32 x
float32 y
float32 z
"""
  __slots__ = ['corner','axes_pts','size']
  _slot_types = ['j2_mono/Point','j2_mono/Point','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       corner,axes_pts,size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OBBox2D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.corner is None:
        self.corner = j2_mono.msg.Point()
      if self.axes_pts is None:
        self.axes_pts = j2_mono.msg.Point()
      if self.size is None:
        self.size = 0.
    else:
      self.corner = j2_mono.msg.Point()
      self.axes_pts = j2_mono.msg.Point()
      self.size = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.corner.x, _x.corner.y, _x.corner.z, _x.axes_pts.x, _x.axes_pts.y, _x.axes_pts.z, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.corner is None:
        self.corner = j2_mono.msg.Point()
      if self.axes_pts is None:
        self.axes_pts = j2_mono.msg.Point()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.corner.x, _x.corner.y, _x.corner.z, _x.axes_pts.x, _x.axes_pts.y, _x.axes_pts.z, _x.size,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.corner.x, _x.corner.y, _x.corner.z, _x.axes_pts.x, _x.axes_pts.y, _x.axes_pts.z, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.corner is None:
        self.corner = j2_mono.msg.Point()
      if self.axes_pts is None:
        self.axes_pts = j2_mono.msg.Point()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.corner.x, _x.corner.y, _x.corner.z, _x.axes_pts.x, _x.axes_pts.y, _x.axes_pts.z, _x.size,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
